### PR TITLE
Adding Spanish language support

### PR DESCRIPTION
**Pull request by MohamedAlaa**
What has been done:

* Adding New Language in the `config/values.js`
* exporting the new language in `src/locale/index.ts`
* Adding the new locale file `src/locale/es.ts`
* Translating the locale file `es.ts` to Spanish

### CODE REVIEW

**Comment by MohamedAlaa** [comment]
@tifa2UP I will keep adding the translation so we can merge it this week. I'm glad it all went fine 👍

**Comment by Ananasship** [comment]
amazing, thank you Mohamed.
ᐧ

**Comment by MohamedAlaa** [comment]
@tifa2UP @Ananasship This branch is ready for your review and Merge :) 

Please let me know once it's deployed so I can test it with my kid.

**Comment by tifa2UP** [comment]
Approved it. Thank you @MohamedAlaa, it'll go out in the next FE deploy insha'Allah

**Pull request merged**
